### ISSUE TITLE
use replaces for view model to avoid having to disable native tab

### ISSUE THREAD

**Issue by jneilliii** [vector76/cnc_gcodeviewer#1]
hey @vector76 while reviewing the plugin I noticed you had a note about disabling the native gcode viewer plugin. you might consider using the replaces option of the [get_template_configs](https://docs.octoprint.org/en/master/plugins/mixins.html#templateplugin) callback. 

I suggested this change for PrettyGCode plugin like [this](https://github.com/jneilliii/OctoPrint-PrettyGCode/blob/master/octoprint_prettygcode/__init__.py#L22), but I think the id has changed since then from `gcodeviewer` to `plugin_gcodeviewer` now.

**Comment by vector76** [comment]
Ok, I don't know how to do that but I will research it and see what I find.

**Comment by vector76** [comment]
Alright, it was not trivial (for me) because I had name collisions (since I had just cloned the existing viewer), but I think this "replaces-viewmodel" approach is now implemented.

Thanks for the feedback, this is nicer, skipping the extra step of disabling the native viewer.
