### ISSUE TITLE
Relative Positioning does not appear to be working

### ISSUE THREAD

**Issue by synman** [vector76/cnc_gcodeviewer#10]
Nothing is rendered in the gcode viewer grid when running grbl jobs that are in relative (G91) positioning mode.  See attached for an example using the "Better Grbl Support" plugin with a laser.

[Margarita.gcode.txt](https://github.com/vector76/cnc_gcodeviewer/files/9998093/Margarita.gcode.txt)

**Comment by vector76** [comment]
Ok, I think I've solved this with version v1.1.1.

Your test case led me to a mistake I had made.  Thankfully, the relative mode (G91) appears to be implemented correctly, and I had made an error in the preprocessing/parsing.

Thank you for the report.

**Comment by synman** [comment]
Thank you!  Grabbing the latest release now.
