### ISSUE TITLE
Current version not working for Lightburn laser Gcode

### ISSUE THREAD

**Issue by thomasdg** [vector76/cnc_gcodeviewer#2]
Was so glad to got this plugin installed as I thought I would finally have a solution to view the gcode for my laser engraver to which I have connected octoprint. Sadly nothing is shown in the viewer when loading a gcode file exported from LightBurn. 
Could have something to do with your remarks on G0 and G1 in the readme :)

Attached is the gcode for a small square (4 passes); maybe it can help you (changed extension to .txt to be able to upload).

[SmallSquare4times.txt](https://github.com/vector76/cnc_gcodeviewer/files/8186094/SmallSquare4times.txt)

**Comment by vector76** [comment]
I'm not an expert on the fine points of gcode syntax dialects.  It would seem that most slicers and CAM processors put a space after the G1/G0 commands.  I believe it is legal to go without them, and while I don't know if Marlin accepts them, grbl evidently does.

Can you configure LightBurn to generate spaces after the G0/G1 commands?  It is probably a good idea for this plugin to support commands without spaces eventually, but it's currently expecting a space.

**Comment by vector76** [comment]
It looks like there is _also_ an issue if the gcode contains no Z coordinates at all.  This needs to be fixed and is separate from the issue of spaces.

**Comment by thomasdg** [comment]
Sadly don't see such an option in the lightburn preferences.
Guess this also confirms this: https://forum.lightburnsoftware.com/t/space-after-g0-and-g1/54010

Of course could write a small find/replace script to use before I upload the file, but would even be better if your plugin could understand space-less gcode :)

Thanks for the quick replies by the way!

**Comment by vector76** [comment]
Alright, I think version 1.0.2 should resolve both of these issues: one, handling the lack of spaces, and two, rendering even if there are no Z movements.

I am new to this and I'm not sure whether the plugin repository will automatically move to 1.0.2 (currently it still shows 1.0.1) or how long it takes to update, but if the repository is not showing 1.0.2 you can always install manually via URL
https://github.com/vector76/cnc_gcodeviewer/archive/refs/tags/v1.0.2.zip
or
https://github.com/vector76/cnc_gcodeviewer/archive/main.zip

I will leave this open in case I missed something, but if this resolves your issue(s) then you can close.

**Comment by thomasdg** [comment]
Installed manually with the URL given and works like a charm now!
